import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavBar from "../../components/NavBar.js";
import { ToastContainer } from "react-toastify";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen overflow-x-hidden`}
      >
        <NavBar />
        <div className="p-5">
          <Suspense>{children}</Suspense>
        </div>
        <ToastContainer />

        <footer className="bg-blue-50 py-12">
          <div className="container mx-auto px-4 text-center text-gray-600">
            <p>Made with 💗 by Yogesh Arya</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
